// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: measurement.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from measurement.proto</summary>
public static partial class MeasurementReflection {

  #region Descriptor
  /// <summary>File descriptor for measurement.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MeasurementReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFtZWFzdXJlbWVudC5wcm90byKtAQoLTWVhc3VyZW1lbnQSEQoJdGltZXN0",
          "YW1wGAEgASgNEh8KBGtpbmQYAiABKA4yES5NZWFzdXJlbWVudC5LaW5kEgwK",
          "BGlkbGUYAyABKA0iXAoES2luZBIICgROT05FEAASDwoLTUVBU1VSRU1FTlQQ",
          "ARIJCgVTVEFSVBACEggKBFNUT1AQAxIQCgxTRVNTSU9OX0xPQ0sQBBISCg5T",
          "RVNTSU9OX1VOTE9DSxAFIlIKDE1lYXN1cmVtZW50cxIQCghpbnRlcnZhbBgB",
          "IAEoDRIMCgR6b25lGAIgASgJEiIKDG1lYXN1cmVtZW50cxgDIAMoCzIMLk1l",
          "YXN1cmVtZW50YgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Measurement), global::Measurement.Parser, new[]{ "Timestamp", "Kind", "Idle" }, null, new[]{ typeof(global::Measurement.Types.Kind) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Measurements), global::Measurements.Parser, new[]{ "Interval", "Zone", "Measurements_" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Measurement : pb::IMessage<Measurement>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Measurement> _parser = new pb::MessageParser<Measurement>(() => new Measurement());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Measurement> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MeasurementReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Measurement() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Measurement(Measurement other) : this() {
    timestamp_ = other.timestamp_;
    kind_ = other.kind_;
    idle_ = other.idle_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Measurement Clone() {
    return new Measurement(this);
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 1;
  private uint timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  /// <summary>Field number for the "kind" field.</summary>
  public const int KindFieldNumber = 2;
  private global::Measurement.Types.Kind kind_ = global::Measurement.Types.Kind.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Measurement.Types.Kind Kind {
    get { return kind_; }
    set {
      kind_ = value;
    }
  }

  /// <summary>Field number for the "idle" field.</summary>
  public const int IdleFieldNumber = 3;
  private uint idle_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Idle {
    get { return idle_; }
    set {
      idle_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Measurement);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Measurement other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Timestamp != other.Timestamp) return false;
    if (Kind != other.Kind) return false;
    if (Idle != other.Idle) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Timestamp != 0) hash ^= Timestamp.GetHashCode();
    if (Kind != global::Measurement.Types.Kind.None) hash ^= Kind.GetHashCode();
    if (Idle != 0) hash ^= Idle.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Timestamp != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Timestamp);
    }
    if (Kind != global::Measurement.Types.Kind.None) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Kind);
    }
    if (Idle != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Idle);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Timestamp != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Timestamp);
    }
    if (Kind != global::Measurement.Types.Kind.None) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Kind);
    }
    if (Idle != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Idle);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Timestamp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Timestamp);
    }
    if (Kind != global::Measurement.Types.Kind.None) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
    }
    if (Idle != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Idle);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Measurement other) {
    if (other == null) {
      return;
    }
    if (other.Timestamp != 0) {
      Timestamp = other.Timestamp;
    }
    if (other.Kind != global::Measurement.Types.Kind.None) {
      Kind = other.Kind;
    }
    if (other.Idle != 0) {
      Idle = other.Idle;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Timestamp = input.ReadUInt32();
          break;
        }
        case 16: {
          Kind = (global::Measurement.Types.Kind) input.ReadEnum();
          break;
        }
        case 24: {
          Idle = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Timestamp = input.ReadUInt32();
          break;
        }
        case 16: {
          Kind = (global::Measurement.Types.Kind) input.ReadEnum();
          break;
        }
        case 24: {
          Idle = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Measurement message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Kind {
      [pbr::OriginalName("NONE")] None = 0,
      [pbr::OriginalName("MEASUREMENT")] Measurement = 1,
      [pbr::OriginalName("START")] Start = 2,
      [pbr::OriginalName("STOP")] Stop = 3,
      [pbr::OriginalName("SESSION_LOCK")] SessionLock = 4,
      [pbr::OriginalName("SESSION_UNLOCK")] SessionUnlock = 5,
    }

  }
  #endregion

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Measurements : pb::IMessage<Measurements>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Measurements> _parser = new pb::MessageParser<Measurements>(() => new Measurements());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Measurements> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MeasurementReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Measurements() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Measurements(Measurements other) : this() {
    interval_ = other.interval_;
    zone_ = other.zone_;
    measurements_ = other.measurements_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Measurements Clone() {
    return new Measurements(this);
  }

  /// <summary>Field number for the "interval" field.</summary>
  public const int IntervalFieldNumber = 1;
  private uint interval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Interval {
    get { return interval_; }
    set {
      interval_ = value;
    }
  }

  /// <summary>Field number for the "zone" field.</summary>
  public const int ZoneFieldNumber = 2;
  private string zone_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Zone {
    get { return zone_; }
    set {
      zone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "measurements" field.</summary>
  public const int Measurements_FieldNumber = 3;
  private static readonly pb::FieldCodec<global::Measurement> _repeated_measurements_codec
      = pb::FieldCodec.ForMessage(26, global::Measurement.Parser);
  private readonly pbc::RepeatedField<global::Measurement> measurements_ = new pbc::RepeatedField<global::Measurement>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Measurement> Measurements_ {
    get { return measurements_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Measurements);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Measurements other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Interval != other.Interval) return false;
    if (Zone != other.Zone) return false;
    if(!measurements_.Equals(other.measurements_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Interval != 0) hash ^= Interval.GetHashCode();
    if (Zone.Length != 0) hash ^= Zone.GetHashCode();
    hash ^= measurements_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Interval != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Interval);
    }
    if (Zone.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Zone);
    }
    measurements_.WriteTo(output, _repeated_measurements_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Interval != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Interval);
    }
    if (Zone.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Zone);
    }
    measurements_.WriteTo(ref output, _repeated_measurements_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Interval != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Interval);
    }
    if (Zone.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Zone);
    }
    size += measurements_.CalculateSize(_repeated_measurements_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Measurements other) {
    if (other == null) {
      return;
    }
    if (other.Interval != 0) {
      Interval = other.Interval;
    }
    if (other.Zone.Length != 0) {
      Zone = other.Zone;
    }
    measurements_.Add(other.measurements_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Interval = input.ReadUInt32();
          break;
        }
        case 18: {
          Zone = input.ReadString();
          break;
        }
        case 26: {
          measurements_.AddEntriesFrom(input, _repeated_measurements_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Interval = input.ReadUInt32();
          break;
        }
        case 18: {
          Zone = input.ReadString();
          break;
        }
        case 26: {
          measurements_.AddEntriesFrom(ref input, _repeated_measurements_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
